/**
 * Metatile atlas manifest.
 *
 * Each atlas is a PNG grid of 16×16 metatiles. The standard atlases
 * (0-7) are 256×256 = 16 columns × 16 rows = 256 metatiles each.
 * Atlas 8 is the enemy sprite atlas. BG strips (0-4) are 4096×16
 * horizontal strips of per-world background tiles.
 *
 * For a metatile ID `n`, the source rectangle in a 256×256 atlas is:
 *   x = (n % 16) * 16
 *   y = Math.floor(n / 16) * 16
 *   width = height = 16
 *
 * Generated by `npm run convert-atlases` from the loginsinex/smb2 repo's
 * bitmap resources (MIT licensed).
 */

import atlas0Url from './atlas-0.png';
import atlas1Url from './atlas-1.png';
import atlas2Url from './atlas-2.png';
import atlas3Url from './atlas-3.png';
import atlas4Url from './atlas-4.png';
import atlas5Url from './atlas-5.png';
import atlas6Url from './atlas-6.png';
import atlas7Url from './atlas-7.png';
import atlas8Url from './atlas-8.png';
import bg0Url from './bg-0.png';
import bg1Url from './bg-1.png';
import bg2Url from './bg-2.png';
import bg3Url from './bg-3.png';
import bg4Url from './bg-4.png';

export const ATLAS_URLS: ReadonlyArray<string> = [
  atlas0Url,
  atlas1Url,
  atlas2Url,
  atlas3Url,
  atlas4Url,
  atlas5Url,
  atlas6Url,
  atlas7Url,
  atlas8Url,
];

/**
 * Ground tile atlases — one per gfx theme (night, day, desert, winter,
 * castle). Horizontal strip format: 4096×16 = 256 tiles of 16×16.
 * Mirrors C++ bmTpl[gfx+10] = bgN.bmp (IDB_BITMAP11-15).
 */
export const BG_ATLAS_URLS: ReadonlyArray<string> = [
  bg0Url,
  bg1Url,
  bg2Url,
  bg3Url,
  bg4Url,
];

export const METATILE_SIZE = 16;
export const ATLAS_COLS = 16;

/**
 * Compute the source rectangle for a metatile ID within a 256×256 atlas.
 */
export function metatileRect(id: number): { sx: number; sy: number } {
  return {
    sx: (id % ATLAS_COLS) * METATILE_SIZE,
    sy: Math.floor(id / ATLAS_COLS) * METATILE_SIZE,
  };
}

/**
 * Compute the source rectangle for a ground tile ID within a BG strip
 * (4096×16 horizontal layout). BG strips hold 256 tiles in one row.
 */
export function bgTileRect(id: number): { sx: number; sy: number } {
  return { sx: id * METATILE_SIZE, sy: 0 };
}

// ─── Image loading ──────────────────────────────────────────────────

const imageCache = new Map<string, HTMLImageElement>();
const loadingCache = new Map<string, Promise<HTMLImageElement>>();

function loadImage(url: string): Promise<HTMLImageElement> {
  const cached = imageCache.get(url);
  if (cached) return Promise.resolve(cached);

  const existing = loadingCache.get(url);
  if (existing) return existing;

  const promise = new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      imageCache.set(url, img);
      loadingCache.delete(url);
      resolve(img);
    };
    img.onerror = () => reject(new Error(`Failed to load atlas: ${url}`));
    img.src = url;
  });
  loadingCache.set(url, promise);
  return promise;
}

/** Get the atlas Image synchronously (null if not yet loaded). */
export function getAtlasImage(index: number): HTMLImageElement | null {
  const url = ATLAS_URLS[index];
  if (!url) return null;
  return imageCache.get(url) ?? null;
}

/** Get the BG atlas Image synchronously (null if not yet loaded). */
export function getBgAtlasImage(gfx: number): HTMLImageElement | null {
  const url = BG_ATLAS_URLS[gfx];
  if (!url) return null;
  return imageCache.get(url) ?? null;
}

/**
 * Pre-load one or more atlas images. Call this before drawing so that
 * `getAtlasImage` returns a non-null value synchronously.
 */
export async function preloadAtlases(indices: number[]): Promise<void> {
  await Promise.all(
    indices
      .map((i) => ATLAS_URLS[i])
      .filter((url): url is string => url !== undefined)
      .map(loadImage),
  );
}

/** Pre-load ALL atlases (call once after ROM load). */
export async function preloadAllAtlases(): Promise<void> {
  await Promise.all([
    ...ATLAS_URLS.map(loadImage),
    ...BG_ATLAS_URLS.map(loadImage),
  ]);
}

// ─── Palette colorization (UseGamma port) ──────────────────────────
//
// Direct port of `CLvlDraw::UseGamma` (clvldraw_render.cpp:300-355).
// For every atlas pixel:
//   clrf  = B | (G<<8) | (R<<16)          // little-endian DWORD, matches x86
//   index = floor(clrf / 0x101010)         // clamped to 15
//   output = palette[index]
// Pixels that were MAGENTA (0xFF 0x00 0xFF) in the source BMP have
// already been marked alpha=0 by `scripts/convert-metatile-atlases.ts`
// — they stay transparent.
//
// This matches C++ exactly: the source BMPs are *not* grayscale but
// pre-colored, and each distinct source color maps to a specific NES
// palette slot via the `clrf / 0x101010` formula.

import type { LevelPalette } from '@/rom/palette-reader';

/**
 * Cache key = "atlasIndex:nesIdx0,nesIdx1,...,nesIdx15".
 * We cache by the actual NES color indices so levels sharing the same
 * palette reuse the same colorized canvas.
 */
const colorizedCache = new Map<string, OffscreenCanvas>();

function paletteKey(atlasIndex: number, palette: LevelPalette): string {
  return `${atlasIndex}:${palette.nesIndices.join(',')}`;
}

/**
 * Get a palette-colorized version of an atlas. Returns an OffscreenCanvas
 * where every grayscale pixel has been remapped through the level's NES
 * palette. Cached per (atlas, palette).
 */
export function getColorizedAtlas(
  atlasIndex: number,
  palette: LevelPalette,
): OffscreenCanvas | null {
  const key = paletteKey(atlasIndex, palette);
  const cached = colorizedCache.get(key);
  if (cached) return cached;

  const srcImg = getAtlasImage(atlasIndex);
  if (!srcImg) return null;

  const w = srcImg.naturalWidth;
  const h = srcImg.naturalHeight;
  const offscreen = new OffscreenCanvas(w, h);
  const ctx = offscreen.getContext('2d');
  if (!ctx) return null;

  // Draw original atlas
  ctx.drawImage(srcImg, 0, 0);
  const imgData = ctx.getImageData(0, 0, w, h);
  const data = imgData.data;

  // Build 16-entry RGB lookup from palette
  const lut: [number, number, number][] = [];
  for (let i = 0; i < 16; i++) {
    lut.push(palette.colors[i] ?? [0, 0, 0]);
  }

  // Remap every pixel via C++ UseGamma formula.
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] === 0) continue; // magenta → already transparent
    const r = data[i]!;
    const g = data[i + 1]!;
    const b = data[i + 2]!;
    const clrf = (r << 16) | (g << 8) | b;
    const idx = Math.min(Math.floor(clrf / 0x101010), 15);
    const color = lut[idx]!;
    data[i] = color[0];
    data[i + 1] = color[1];
    data[i + 2] = color[2];
  }

  ctx.putImageData(imgData, 0, 0);
  colorizedCache.set(key, offscreen);
  return offscreen;
}

/**
 * Palette-colorize a BG ground atlas (horizontal strip 4096×16).
 * Same grayscale-remap logic as getColorizedAtlas, different source.
 */
const bgColorizedCache = new Map<string, OffscreenCanvas>();

export function getColorizedBgAtlas(
  gfx: number,
  palette: LevelPalette,
): OffscreenCanvas | null {
  const key = `bg${gfx}:${palette.nesIndices.join(',')}`;
  const cached = bgColorizedCache.get(key);
  if (cached) return cached;

  const srcImg = getBgAtlasImage(gfx);
  if (!srcImg) return null;

  const w = srcImg.naturalWidth;
  const h = srcImg.naturalHeight;
  const offscreen = new OffscreenCanvas(w, h);
  const ctx = offscreen.getContext('2d');
  if (!ctx) return null;

  ctx.drawImage(srcImg, 0, 0);
  const imgData = ctx.getImageData(0, 0, w, h);
  const data = imgData.data;

  const lut: [number, number, number][] = [];
  for (let i = 0; i < 16; i++) {
    lut.push(palette.colors[i] ?? [0, 0, 0]);
  }

  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] === 0) continue;
    const r = data[i]!;
    const g = data[i + 1]!;
    const b = data[i + 2]!;
    const clrf = (r << 16) | (g << 8) | b;
    const idx = Math.min(Math.floor(clrf / 0x101010), 15);
    const color = lut[idx]!;
    data[i] = color[0];
    data[i + 1] = color[1];
    data[i + 2] = color[2];
  }

  ctx.putImageData(imgData, 0, 0);
  bgColorizedCache.set(key, offscreen);
  return offscreen;
}

/** Clear the colorized atlas cache (call on ROM unload). */
export function clearColorizedCache(): void {
  colorizedCache.clear();
  bgColorizedCache.clear();
}
