/**
 * Metatile atlas manifest.
 *
 * Each atlas is a PNG grid of 16×16 metatiles. The standard atlases
 * (0-7) are 256×256 = 16 columns × 16 rows = 256 metatiles each.
 * Atlas 8 is the enemy sprite atlas. BG strips (0-4) are 4096×16
 * horizontal strips of per-world background tiles.
 *
 * For a metatile ID `n`, the source rectangle in a 256×256 atlas is:
 *   x = (n % 16) * 16
 *   y = Math.floor(n / 16) * 16
 *   width = height = 16
 *
 * Generated by `npm run convert-atlases` from the loginsinex/smb2 repo's
 * bitmap resources (MIT licensed).
 */

import atlas0Url from './atlas-0.png';
import atlas1Url from './atlas-1.png';
import atlas2Url from './atlas-2.png';
import atlas3Url from './atlas-3.png';
import atlas4Url from './atlas-4.png';
import atlas5Url from './atlas-5.png';
import atlas6Url from './atlas-6.png';
import atlas7Url from './atlas-7.png';
import atlas8Url from './atlas-8.png';

export const ATLAS_URLS: ReadonlyArray<string> = [
  atlas0Url,
  atlas1Url,
  atlas2Url,
  atlas3Url,
  atlas4Url,
  atlas5Url,
  atlas6Url,
  atlas7Url,
  atlas8Url,
];

export const METATILE_SIZE = 16;
export const ATLAS_COLS = 16;

/**
 * Compute the source rectangle for a metatile ID within a 256×256 atlas.
 */
export function metatileRect(id: number): { sx: number; sy: number } {
  return {
    sx: (id % ATLAS_COLS) * METATILE_SIZE,
    sy: Math.floor(id / ATLAS_COLS) * METATILE_SIZE,
  };
}

// ─── Image loading ──────────────────────────────────────────────────

const imageCache = new Map<string, HTMLImageElement>();
const loadingCache = new Map<string, Promise<HTMLImageElement>>();

function loadImage(url: string): Promise<HTMLImageElement> {
  const cached = imageCache.get(url);
  if (cached) return Promise.resolve(cached);

  const existing = loadingCache.get(url);
  if (existing) return existing;

  const promise = new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      imageCache.set(url, img);
      loadingCache.delete(url);
      resolve(img);
    };
    img.onerror = () => reject(new Error(`Failed to load atlas: ${url}`));
    img.src = url;
  });
  loadingCache.set(url, promise);
  return promise;
}

/** Get the atlas Image synchronously (null if not yet loaded). */
export function getAtlasImage(index: number): HTMLImageElement | null {
  const url = ATLAS_URLS[index];
  if (!url) return null;
  return imageCache.get(url) ?? null;
}

/**
 * Pre-load one or more atlas images. Call this before drawing so that
 * `getAtlasImage` returns a non-null value synchronously.
 */
export async function preloadAtlases(indices: number[]): Promise<void> {
  await Promise.all(
    indices
      .map((i) => ATLAS_URLS[i])
      .filter((url): url is string => url !== undefined)
      .map(loadImage),
  );
}

/** Pre-load ALL atlases (call once after ROM load). */
export async function preloadAllAtlases(): Promise<void> {
  await preloadAtlases(ATLAS_URLS.map((_, i) => i));
}
